name: glownepal_mobile_app_5th_sem
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.14
  font_awesome_flutter: ^10.8.0
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.4
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  bloc: ^8.1.4
  connectivity_plus: ^6.1.1
  json_serializable: ^6.9.0
  flutter_bloc: ^8.1.6
  permission_handler: ^11.3.1
  curved_navigation_bar: ^1.0.6
  sensors_plus: ^6.1.1
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  test_cov_console: ^0.2.2
  coverage: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          # style: italic

    - family: Montserrat Italic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf
          
    
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300


flutter_native_splash:
  color: "#ffffff" 
  image: assets/logos/glow-nepal-splash-logo.png 
  android: true
  ios: true
  fullscreen: true
