name: glownepal_mobile_app_5th_sem
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/logos/glow-nepal-splash-logo.png # Path to your logo
  android: true
  ios: true
  fullscreen: true
