name: glownepal_mobile_app_5th_sem
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.14
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          # style: italic

    - family: Montserrat Italic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf
          
    
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf


flutter_native_splash:
  color: "#ffffff" 
  image: assets/logos/glow-nepal-splash-logo.png 
  android: true
  ios: true
  fullscreen: true
